
import { Billboard } from "./types";

const RAW_DATA = [
  {
    "CODIGO_PROVEEDOR": "AGS-001 A",
    "ELEMENTO": "AGS-001",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. José Carlos Mariátegui",
    "DIRECCION_LEGAL": "Av. José Carlos Mariátegui – Puente Nuevo (Evitamiento)",
    "TRANSITO": "Hacia Vía Evitamiento con dirección a Zarate San Juan de Lurigancho.",
    "REFERENCIA": "Frente Puente Nuevo. Próximo a Plaza Vea.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0303310",
    "LONGITUD": "-76.9998470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "8,569,847",
    "URLIMAGEN": "",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-001 B",
    "ELEMENTO": "AGS-001",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. José Carlos Mariátegui ",
    "DIRECCION_LEGAL": "Av. José Carlos Mariátegui – Puente Nuevo (Evitamiento)",
    "TRANSITO": "Hacia el norte Av. Ferrocarril el Agustino.",
    "REFERENCIA": "Frente Puente Nuevo. Próximo a Plaza Vea.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0303310",
    "LONGITUD": "-76.9998470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "9,807,017",
    "URLIMAGEN": "",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-003 A",
    "ELEMENTO": "AGS-003",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N cruce con Av. Robert Fulton",
    "TRANSITO": "Hacia el sur con dirección al Puente Santa Anita",
    "REFERENCIA": "Frente al paradero Villa Hermosa",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0419330",
    "LONGITUD": "-76.9873040",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "11,348,387",
    "URLIMAGEN": "",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-003 B",
    "ELEMENTO": "AGS-003",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N cruce con Av. Robert Fulton",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "URLIMAGEN": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-004 A",
    "ELEMENTO": "AGS-004",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento cruce con Av. Los Ficus",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "URLIMAGEN": "https://lh3.googleusercontent.com/rd-d/ALs6j_EW8n5Ka1JTErhXrPPDWEexmXn5Q-pv5xGkvrR-8abz-1kxCERDwIwgeUSx4AzwG21OY7SdhOdTWwxHKWufkId3Qg5BbEWacOn0kgWU57KmM466j_pVDH0tYsKY6m9_NL90xVYFdm22wBBLZX49UM55zWaiwqGq0cqxXuzr56rylC36asB_5Q1ox7mvkfiNPSxnhP7IvZAVUIV0lQdDBv0T2H4CKc0zT0aWjRnjs4K_IHCccQa6Ku4A5Bh2G1chhg_GGw2leuxbjPEhDRhAT5kVQ8kirsRuTN5hkjpz2todoY5xvKmbsh8efaPe-zao3iM9wdI6TOk4wFQzKGwepC8dqtWP9ff7c2gg3Hj2LyVEuLNsFTvJYy1CXAeqQSgnuiynQa5c1o7iVUcaJ9LvkKHaDbcdr1bzMi-Uaf8Z6mSurqABvNpLQSbWV-zSn-74eXT4bal9u1qsPQVAVJz9wxyFZ-0KX7jLzpjylkYqkT80QDp_dhYWLhb1E-Y0YdbdqgvgnDq1vYijdj_kXPOAxYgvsd6ZjRbuk2Zjis0WqVo4Pz9JVhwq47FaA-faCv0fAtAP0cQWXBw1dhFI2Krfr3P6yKq6FVaXUAakA0FtPI7iWYObDDpZi7HZeMAUZpKa-0_2GTNEez0FXIvcLKU0PCw7Z8jRHr-a3DaSI6Ebnl9Rd4OO9nAQulWl1-0femphYrpmjOKHSJzYjFSsxqUxlgXc9bFO0Zozq6u04Xpg2wby5xa6UAvsVZeNFYNKE-gPGPEXm4QtDwc69tUm5PYKB_CSCwjF1yFZWG8PmYnm1fR0DfKQqwZM17OfFU3wQiXWnbcNoXBNivA1lmsxmziBmVT-jwQ-7D9vZg22GALhevIO7RrezltJBFcsuN7dddBBtjUf5JVtm3YWg_PfcmKIl6JhUR7js40L9y-WFeX1YR-l7js2iQPJYNaBXsxIlxDVVeTMbO2Jj9CM10Ika4EQmul9TrCl2dYu4Y07xh9JLJfpLq9uITQOjNmUOPM0AQZwxAfSE2AGTA=w1920-h911?auditContext=thumbnail&auditContext=prefetch",
    "PROPIEDAD": ""
  }
  ];

// Transform logic and export
export const INVENTORY: Billboard[] = RAW_DATA
  // Hemos relajado el filtro. Ahora solo validamos que exista un código.
  // Ya no filtramos por latitud para que aparezcan los 5 elementos aunque no tengan mapa.
  .filter(item => item.CODIGO_PROVEEDOR)
  .map((item, index) => ({
    id: `${item.CODIGO_PROVEEDOR}-${index}`,
    codigo: item.CODIGO_PROVEEDOR || '',
    elemento: item.ELEMENTO || '',
    cara: item.CARA || '',
    formato: item.FORMATO || '',
    distrito: item.DISTRITO || '',
    tipo: item.TIPO || '',
    medida: item.MEDIDA || '',
    ancho: item.ANCHO || '',
    alto: item.ALTO || '',
    audiencia: parseInt((item.AUDIENCIA || '0').replace(/,/g, ''), 10) || 0,
    direccionComercial: item.DIRECCION_COMERCIAL || '',
    direccionLegal: item.DIRECCION_LEGAL || '',
    departamento: item.DEPARTAMENTO || '',
    zona: item.ZONA || '',
    latitud: parseFloat(item.LATITUD || '0') || 0,
    longitud: parseFloat(item.LONGITUD || '0') || 0,
    observacion: item.OBSERVACION || '',
    // Aquí se lee el campo URLIMAGEN de tus datos JSON.
    // Si está vacío, se usa la imagen de ejemplo de Google Drive.
    urlImagen: (item as any).URLIMAGEN || 'https://lh3.googleusercontent.com/d/1uxyWs3IyODVTbTszArRKiMS3JsloML-j=w1000?authuser=0' 
  }));

export const DEPARTMENT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.departamento).filter(Boolean))).sort();
export const DISTRICT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.distrito).filter(Boolean))).sort();
export const ELEMENT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.elemento).filter(Boolean))).sort();
export const TYPE_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.tipo).filter(Boolean))).sort();
export const ZONE_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.zona).filter(Boolean))).sort();
