
import { Billboard } from "./types";

const RAW_DATA = [
  {
    "CODIGO_PROVEEDOR": "AGS-001 A",
    "ELEMENTO": "AGS-001",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. José Carlos Mariátegui",
    "DIRECCION_LEGAL": "Av. José Carlos Mariátegui – Puente Nuevo (Evitamiento)",
    "TRANSITO": "Hacia Vía Evitamiento con dirección a Zarate San Juan de Lurigancho.",
    "REFERENCIA": "Frente Puente Nuevo. Próximo a Plaza Vea.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0303310",
    "LONGITUD": "-76.9998470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "8,569,847",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-001 B",
    "ELEMENTO": "AGS-001",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. José Carlos Mariátegui ",
    "DIRECCION_LEGAL": "Av. José Carlos Mariátegui – Puente Nuevo (Evitamiento)",
    "TRANSITO": "Hacia el norte Av. Ferrocarril el Agustino.",
    "REFERENCIA": "Frente Puente Nuevo. Próximo a Plaza Vea.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0303310",
    "LONGITUD": "-76.9998470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "9,807,017",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-003 A",
    "ELEMENTO": "AGS-003",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N cruce con Av. Robert Fulton",
    "TRANSITO": "Hacia el sur con dirección al Puente Santa Anita",
    "REFERENCIA": "Frente al paradero Villa Hermosa",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0419330",
    "LONGITUD": "-76.9873040",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "11,348,387",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-003 B",
    "ELEMENTO": "AGS-003",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N cruce con Av. Robert Fulton",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el norte con dirección el Rimac.\"",
    "ELEMENTO": "Frente al paradero Villa Hermosa",
    "CARA": "14.40X7.20",
    "FORMATO": "14.4",
    "TIPO": "7.2",
    "PROVEEDOR": "103.68",
    "DEPARTAMENTO": "-12.0419330",
    "DISTRITO": "-76.9873040",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "PARA IMPULSAR",
    "TRANSITO": "11,348,387",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-004 A",
    "ELEMENTO": "AGS-004",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento cruce con Av. Los Ficus",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el sur con dirección al puente Santa Anita – Av. Nicolás Ayllón\"",
    "ELEMENTO": "Frente a paradero El Pino",
    "CARA": "14.40X7.20",
    "FORMATO": "14.4",
    "TIPO": "7.2",
    "PROVEEDOR": "103.68",
    "DEPARTAMENTO": "-12.0535280",
    "DISTRITO": "-76.9756770",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "8,971,071",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-004 B",
    "ELEMENTO": "AGS-004",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento cruce con Av. Los Ficus",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "De sur a norte hacia puente nuevo Panamericana Norte.\"",
    "ELEMENTO": "Frente a paradero El Pino",
    "CARA": "14.40X7.20",
    "FORMATO": "14.4",
    "TIPO": "7.2",
    "PROVEEDOR": "103.68",
    "DEPARTAMENTO": "-12.0535280",
    "DISTRITO": "-76.9756770",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "10,097,353",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-005 A",
    "ELEMENTO": "AGS-005",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N – Panamericana Norte",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el Sur con dirección al Puente Nuevo\"",
    "ELEMENTO": "Próximo a Emp. Mepsa Plaza Vea y Emp. Trupal",
    "CARA": "14.40X7.20",
    "FORMATO": "14.4",
    "TIPO": "7.2",
    "PROVEEDOR": "103.68",
    "DEPARTAMENTO": "-12.0323740",
    "DISTRITO": "-77.0051380",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "4,874,781",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-005 B",
    "ELEMENTO": "AGS-005",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N – Panamericana Norte",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el norte Centro de Lima Mercado de Flores.\"",
    "ELEMENTO": "Próximo a Emp. Mepsa Plaza Vea y Emp. Trupal",
    "CARA": "14.40X7.20",
    "FORMATO": "14.4",
    "TIPO": "7.2",
    "PROVEEDOR": "103.68",
    "DEPARTAMENTO": "-12.0323740",
    "DISTRITO": "-77.0051380",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "10,648,556",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-006 A",
    "ELEMENTO": "AGS-006",
    "CARA": "A",
    "FORMATO": "Unipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA DIGITAL",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N – Puente Nuevo",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el sur con dirección al puente Santa Anita\"",
    "ELEMENTO": "Frente a Puente Nuevo próximo a Sodimac de San Juan de Lurigancho",
    "CARA": "12.00X6.00",
    "FORMATO": "12",
    "TIPO": "6",
    "PROVEEDOR": "72",
    "DEPARTAMENTO": "-12.0303690",
    "DISTRITO": "-77.0000140",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "11,354,263",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-006 B",
    "ELEMENTO": "AGS-006",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento ",
    "DIRECCION_LEGAL": "Vía Evitamiento S/N – Puente Nuevo",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Hacia el centro de Lima\"",
    "ELEMENTO": "Próximo a Plaza Vea con dirección a Mercado de Flores",
    "CARA": "12.40X6.20",
    "FORMATO": "12.4",
    "TIPO": "6.2",
    "PROVEEDOR": "76.88",
    "DEPARTAMENTO": "-12.0303690",
    "DISTRITO": "-77.0000140",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "11,350,603",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "AGS-007 A",
    "ELEMENTO": "AGS-007",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Jr. Áncash Con Óvalo La Paz",
    "DIRECCION_LEGAL": "Jr. Áncash cruce con el Óvalo la paz",
    "TRANSITO": "Óvalo La Paz que desemboca para Centro de Lima  San Juan de Lurigancho y Santa Anita",
    "REFERENCIA": "Próximo al Mall Parque Agustino Hospital de la Solidaridad.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0403653",
    "LONGITUD": "-76.9977524",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "5,463,909",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "AGS-007 B",
    "ELEMENTO": "AGS-007",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "El Agustino",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Jr. Áncash Con Óvalo La Paz",
    "DIRECCION_LEGAL": "Jr. Áncash cruce con el Óvalo la paz",
    "TRANSITO": "",
    "REFERENCIA": "",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "Óvalo La Paz que desemboca a San Juan de Lurigancho y Santa Anita\"",
    "ELEMENTO": "Próximo al Mall Parque Agustino y Hospital de la Solidaridad.",
    "CARA": "8.00X4.00",
    "FORMATO": "8",
    "TIPO": "4",
    "PROVEEDOR": "32",
    "DEPARTAMENTO": "-12.0403692",
    "DISTRITO": "-76.9977551",
    "ZONA": "",
    "DIRECCION_COMERCIAL": "DISPONIBLE",
    "DIRECCION_LEGAL": "COMERCIAL",
    "TRANSITO": "5,018,331",
    "REFERENCIA": "VP",
    "MEDIDA": "",
    "ANCHO": "",
    "ALTO": "",
    "AREA": "",
    "LATITUD": "",
    "LONGITUD": "",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "",
    "CONDICION_MERCADO": "",
    "AUDIENCIA": "",
    "PROPIEDAD": ""
  },
  {
    "CODIGO_PROVEEDOR": "ANT-001 A",
    "ELEMENTO": "ANT-001",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Acceso A La Panamericana Norte",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central) con Acceso a la Panamericana Norte",
    "TRANSITO": "Hacia El Agustino e ingreso a Vía Evitamiento",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "12.10X6.05",
    "ANCHO": "12.1",
    "ALTO": "6.05",
    "AREA": "73.205",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,825,523",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-001 B",
    "ELEMENTO": "ANT-001",
    "CARA": "B",
    "FORMATO": "Unipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón (Carretera Central) ",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón S/N (Carretera Central)",
    "TRANSITO": "Hacia el Óvalo Santa Anita.",
    "REFERENCIA": "Frente a C.C. Santa Anita puerta principal Saga Falabella.",
    "MEDIDA": "12.10X6.05",
    "ANCHO": "12.1",
    "ALTO": "6.05",
    "AREA": "73.205",
    "LATITUD": "-12.0571910",
    "LONGITUD": "-76.9709540",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "10,903,401",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-002 A",
    "ELEMENTO": "ANT-002",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Av. Los Cipreses",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllon (Carretera Central)",
    "TRANSITO": "De Santa Anita hacia El Agustino e ingreso a Vía Evitamiento",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,214,346",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-002 B",
    "ELEMENTO": "ANT-002",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Av. Los Cipreses",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central)",
    "TRANSITO": "Hacia Ate Vitarte",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "contra el trafico, altotránsito peatonal ",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "3,215,241",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-003 A",
    "ELEMENTO": "ANT-003",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Minería ",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central)",
    "TRANSITO": "De Santa Anita hacia El Agustino e ingreso a Vía Evitamiento",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,820,950",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-003 B",
    "ELEMENTO": "ANT-003",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Minería ",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central)",
    "TRANSITO": "Hacia Ate Vitarte",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,348,887",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-004 A",
    "ELEMENTO": "ANT-004",
    "CARA": "A",
    "FORMATO": "Minipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. Nicolas Ayllon (Carretera Central)",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central) Cdra. 30",
    "TRANSITO": "Hacia Vía Evitamiento con dirección al distrito de El Agustino",
    "REFERENCIA": "Frente al C.C. Mall Aventura Ripley Sagafalabella Bancos y más",
    "MEDIDA": "8.96X3.84",
    "ANCHO": "8.96",
    "ALTO": "3.84",
    "AREA": "34.4064",
    "LATITUD": "-12.0568523",
    "LONGITUD": "-76.9699033",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "8,171,344",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-004 B",
    "ELEMENTO": "ANT-004",
    "CARA": "B",
    "FORMATO": "Torre minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Frente Al C.C. Mall Aventura Plaza",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central) cdra. 30",
    "TRANSITO": "Hacia Av. Los Ruiseñores",
    "REFERENCIA": "Frente al C.C. Mall Aventura Ripley Sagafalabella Bancos y más",
    "MEDIDA": "9.00X4.10",
    "ANCHO": "9",
    "ALTO": "4.1",
    "AREA": "36.9",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,348,973",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-005 A",
    "ELEMENTO": "ANT-005",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Cdra. 30 ",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central) Cdra. 30",
    "TRANSITO": "Hacia el Agustino y Vía Evitamiento",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,801,553",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-005 B",
    "ELEMENTO": "ANT-005",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Cdra. 30",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón (Carretera Central) Cdra. 30",
    "TRANSITO": "Hacia el Ovalo de Santa Anita y Ate Vitarte.",
    "REFERENCIA": "Frente a Mall Aventura Santa Anita.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0571710",
    "LONGITUD": "-76.9706190",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "6,386,010",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-006 A",
    "ELEMENTO": "ANT-006",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Via Evitamiento Con Emilio Fort",
    "DIRECCION_LEGAL": "Via Evitamiento cruce con Emilio Fort",
    "TRANSITO": "Hacia el Agustino",
    "REFERENCIA": "Frente a Empresa Ancro y DEX Coberdex",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0546000",
    "LONGITUD": "-76.9745640",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "11,348,387",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-006 B",
    "ELEMENTO": "ANT-006",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Vía Evitamiento Con Emilio Fort",
    "DIRECCION_LEGAL": "Via Evitamiento cruce con Emilio Fort",
    "TRANSITO": "Hacia Santa Anita.",
    "REFERENCIA": "Frente a Empresa Ancro y DEX Coberdex",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0546000",
    "LONGITUD": "-76.9745640",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "11,348,387",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-007 A",
    "ELEMENTO": "ANT-007",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Av. De La Cultura",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón con Av. De La Cultura",
    "TRANSITO": "Hacia Santa Anita.",
    "REFERENCIA": "Frente al Hospital Hermilio Baldizan.",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0463680",
    "LONGITUD": "-76.9447260",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,803,786",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-007 B",
    "ELEMENTO": "ANT-007",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Con Av. De La Cultura",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón con Av. De La Cultura",
    "TRANSITO": "Hacia Ate Vitarte.",
    "REFERENCIA": "Frente al Hospital Hermilio Baldizan.",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-12.0463680",
    "LONGITUD": "-76.9447260",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,556,856",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-010 A",
    "ELEMENTO": "ANT-010",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. De La Cultura Con 24 Junio",
    "DIRECCION_LEGAL": "Av. De La Cultura con 24 de Junio",
    "TRANSITO": "Hacia Campoy y Ramiro Priale.",
    "REFERENCIA": "Frente al Mercado de Productores Santa Anita",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0412820",
    "LONGITUD": "-76.9468920",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "1,962,060",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ANT-010 B",
    "ELEMENTO": "ANT-010",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Santa Anita",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. De La Cultura Con 24 Junio",
    "DIRECCION_LEGAL": "Av. De La Cultura con 24 Junio",
    "TRANSITO": "Hacia Santa Anita y Carretera Central",
    "REFERENCIA": "Frente al Mercado de Productores Santa Anita",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0412820",
    "LONGITUD": "-76.9468920",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,520,159",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-008 A",
    "ELEMENTO": "ARQ-008",
    "CARA": "A",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. El Ejército Con Av. Cayma",
    "DIRECCION_LEGAL": "Av. El Ejército cdra. 9 cruce con Av. Cayma (Al costado de Scotiabank)",
    "TRANSITO": "Hacia el C.C. Real Plaza con dirección a la Av. Aviación",
    "REFERENCIA": "Frente a Scotiabank y rodeado de diversos negocios locales",
    "MEDIDA": "9.00X10.00",
    "ANCHO": "9",
    "ALTO": "10",
    "AREA": "90",
    "LATITUD": "-16.3893560",
    "LONGITUD": "-71.5477470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,927,489",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-008 B",
    "ELEMENTO": "ARQ-008",
    "CARA": "B",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. El Ejército Con Av. Cayma",
    "DIRECCION_LEGAL": "Av. El Ejército cdra. 9 cruce con Av. Cayma (Al costado de Scotiabank)",
    "TRANSITO": "Hacia C.C. Mall Plaza y Plaza de Armas de Arequipa",
    "REFERENCIA": "Frente a Scotiabank y rodeado de diversos negocios locales",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.3893560",
    "LONGITUD": "-71.5477470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,804,909",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-012 U",
    "ELEMENTO": "ARQ-012",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Dolores cruce con Av. Los Incas",
    "DIRECCION_LEGAL": "URB. Los Rosales MZ E LT 1",
    "TRANSITO": "Intersección hacia parque Lambramani hospital regional óvalo Dolores o Av. Venezuela.",
    "REFERENCIA": "A 05 cdras del parque Lambrani",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.4136604",
    "LONGITUD": "-71.5279514",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,892,544",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-014 U",
    "ELEMENTO": "ARQ-014",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Andrés Avelino Cáceres Altos",
    "DIRECCION_LEGAL": "Av. Andrés Avelino Cáceres Altos – Centro comercial Vista Alegre",
    "TRANSITO": "Hacia Av. Los Incas con dirección a Vía Evitamiento.",
    "REFERENCIA": "Próximo a Makro",
    "MEDIDA": "13.00X6.50",
    "ANCHO": "13",
    "ALTO": "6.5",
    "AREA": "84.5",
    "LATITUD": "-16.4251190",
    "LONGITUD": "-71.5368140",
    "OBSERVACION": "Tapado ligramente en el lado inferior derecho.",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,370,424",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-015 U",
    "ELEMENTO": "ARQ-015",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. El Ejército ",
    "DIRECCION_LEGAL": "Av. El Ejército cdra. 10",
    "TRANSITO": "Hacia el Real Plaza y el centro histórico de Arequipa.",
    "REFERENCIA": "Frente a Chevrolet",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3888940",
    "LONGITUD": "-71.5491790",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,362,983",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-019 A",
    "ELEMENTO": "ARQ-019",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Variante De Uchumayo",
    "DIRECCION_LEGAL": "Variante de Uchumayo",
    "TRANSITO": "Hacia intercambio vial con Av. Parra y Av. Alfonso Ugarte.",
    "REFERENCIA": "Próximo a Backus Senati IncaTops",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.4152604",
    "LONGITUD": "-71.5519207",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,469,831",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-019 B",
    "ELEMENTO": "ARQ-019",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Variante De Uchumayo",
    "DIRECCION_LEGAL": "Variante de Uchumayo",
    "TRANSITO": "Hacia Av. Arrayanes con dirección a la planta Backus.",
    "REFERENCIA": "Próximo a Backus Senati IncaTops",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.4151086",
    "LONGITUD": "-71.5519958",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,446,170",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-025 U",
    "ELEMENTO": "ARQ-025",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Porongoche 508",
    "DIRECCION_LEGAL": "Av. Porongoche 508",
    "TRANSITO": "Hacia Av. Los Incas con dirección al Distrito de Mariano Melgar",
    "REFERENCIA": "Frente al Mall Aventura Plaza al costado de estilos",
    "MEDIDA": "9.70X10.00",
    "ANCHO": "9.7",
    "ALTO": "10",
    "AREA": "97",
    "LATITUD": "-16.4166440",
    "LONGITUD": "-71.5156800",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,935,367",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-026 A",
    "ELEMENTO": "ARQ-026",
    "CARA": "A",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. El Ejército 706",
    "DIRECCION_LEGAL": "Av. El Ejército 706 – Distrito de Cerro Colorado",
    "TRANSITO": "Hacia el C.C Real Plaza y Av. Cayma",
    "REFERENCIA": "Frente al grifo Primax.",
    "MEDIDA": "12.00X6.00",
    "ANCHO": "12",
    "ALTO": "6",
    "AREA": "72",
    "LATITUD": "-16.3849590",
    "LONGITUD": "-71.5550550",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,186,024",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-026 B",
    "ELEMENTO": "ARQ-026",
    "CARA": "B",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. El Ejército ",
    "DIRECCION_LEGAL": "Av. El Ejército 706 – Distrito de Cerro Colorado",
    "TRANSITO": "Hacia el CC Arequipa Center, Aeropuerto, Av. Aviación, Fabrica Soccosani",
    "REFERENCIA": "Costado Grifo Primax.",
    "MEDIDA": "11.00X6.50",
    "ANCHO": "11",
    "ALTO": "6.5",
    "AREA": "71.5",
    "LATITUD": "-16.3849590",
    "LONGITUD": "-71.5550550",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,284,591",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-034 A",
    "ELEMENTO": "ARQ-034",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación frente a Arequipa Center",
    "DIRECCION_LEGAL": "Av. Aviación frente a Arequipa Center",
    "TRANSITO": "Hacia el centro histórico de Arequipa.",
    "REFERENCIA": "Cerca al Arequipa Center, Metro y tiendas por departamento.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3758337",
    "LONGITUD": "-71.5575434",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,864,117",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-034 B",
    "ELEMENTO": "ARQ-034",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación frente a Arequipa Center",
    "DIRECCION_LEGAL": "Av. Aviación frente a Arequipa Center",
    "TRANSITO": "Hacia Av. El Ejercito, Real Plaza Arequipa, distrito de Yanahuara",
    "REFERENCIA": "Cerca al Arequipa Center, Metro y tiendas por departamento.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3758337",
    "LONGITUD": "-71.5575434",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,897,636",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-035 A",
    "ELEMENTO": "ARQ-035",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Vía Yura Km. 1",
    "DIRECCION_LEGAL": "Vía Yura Km. 1",
    "TRANSITO": "Hacia Av. Aviación, ingreso al Aeropuerto, Plaza Las Américas, Metro Maestro Cerro Colorad.",
    "REFERENCIA": "Frente Centro Comercial Arequipa Norte, Plaza Norte y Grifo Petro Perú.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3759722",
    "LONGITUD": "-71.5571667",
    "OBSERVACION": "Elemento con Reflector Solar Lado",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,985,043",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-035 B",
    "ELEMENTO": "ARQ-035",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Vía Yura Km. 1",
    "DIRECCION_LEGAL": "Vía Yura Km. 1",
    "TRANSITO": "Hacia Óvalo Arequipa – La Joya, Plaza Menor de Ciudad de Dios, Municipalidad Distrital de Yura.",
    "REFERENCIA": "Frente Centro Comercial Arequipa Norte, Plaza Norte y Grifo Petro Perú",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3759722",
    "LONGITUD": "-71.5571667",
    "OBSERVACION": "Elemento con Reflector Solar Lado",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,112,864",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-038 A",
    "ELEMENTO": "ARQ-038",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación con Av. Aeropuerto",
    "DIRECCION_LEGAL": "Av. Aviación con Av. Aeropuerto",
    "TRANSITO": "Hacia salida al aeropuerto internacional.",
    "REFERENCIA": "Frente al Monumento a la Libertad sentada, salida al Aeropuerto internacional Alfredo Rodriguez Ballón.",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.3524262",
    "LONGITUD": "-71.5690744",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,699,644",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-038 B",
    "ELEMENTO": "ARQ-038",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación con Av. Aeropuerto",
    "DIRECCION_LEGAL": "Av. Aviación con Av. Aeropuerto",
    "TRANSITO": "Hacia salida al aeropuerto internacional.",
    "REFERENCIA": "Frente al Monumento a la Libertad sentada, salida al Aeropuerto internacional Alfredo Rodriguez Ballón.",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.3524262",
    "LONGITUD": "-71.5690744",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,699,644",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-041 U",
    "ELEMENTO": "ARQ-041",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Parra ",
    "DIRECCION_LEGAL": "Av. Parra 207 - 209",
    "TRANSITO": "Hacia Av. Sucre, Centro histórico, Plaza de armas.",
    "REFERENCIA": "Próximo a Tottus, Decorcenter, costado de UTP",
    "MEDIDA": "12.00X6.00",
    "ANCHO": "12",
    "ALTO": "6",
    "AREA": "72",
    "LATITUD": "-16.4087390",
    "LONGITUD": "-71.5425230",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,386,250",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-044 A",
    "ELEMENTO": "ARQ-044",
    "CARA": "A",
    "FORMATO": "Unipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. Ejército",
    "DIRECCION_LEGAL": "Av. Ejercito cdra.3 cruce con Calle Ampatacocha",
    "TRANSITO": "Hacia Av. La Marina con dirección a la Plaza de armas y Monasterio Santa Catalina",
    "REFERENCIA": "A 2 cdras. Del Real Plaza / Mall Plaza Cayma / Metro / Plaza Vea.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3911310",
    "LONGITUD": "-71.5433540",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,601,553",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-044 B",
    "ELEMENTO": "ARQ-044",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Ejército Con Calle Ampatacocha",
    "DIRECCION_LEGAL": "Av. Ejército cdra. 3 cruce con Calle Ampatacocha",
    "TRANSITO": "Hacia Av. Cayma con dirección a los centros comerciales Mall Plaza Cayma y Real Plaza.",
    "REFERENCIA": "Rodeado de diversos negocios locales bancos y supermercados.",
    "MEDIDA": "10.40X5.45",
    "ANCHO": "10.4",
    "ALTO": "5.45",
    "AREA": "56.68",
    "LATITUD": "-16.3911310",
    "LONGITUD": "-71.5433540",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "7,468,560",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-046 A",
    "ELEMENTO": "ARQ-046",
    "CARA": "A",
    "FORMATO": "Minipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. Los Incas ",
    "DIRECCION_LEGAL": "Av. Los Incas – Cercado de Arequipa ",
    "TRANSITO": "Hacia Av. Jesús con dirección a Paucarpata.",
    "REFERENCIA": "Frente a la puerta principal del C.C. y Parque Lambramani.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-16.4108478",
    "LONGITUD": "-71.5203060",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,492,486",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-046 B",
    "ELEMENTO": "ARQ-046",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Los Incas – Cercado De Arequipa",
    "DIRECCION_LEGAL": "Av. Los Incas – Cercado de Arequipa ",
    "TRANSITO": "Hacia Av. Lambramani con dirección al parque central.",
    "REFERENCIA": "Frente a la puerta principal del C.C. y parque Lambramani.",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-16.4109440",
    "LONGITUD": "-71.5207420",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "5,007,933",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-047 U",
    "ELEMENTO": "ARQ-047",
    "CARA": "U",
    "FORMATO": "Panel",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Alfonso Ugarte 203",
    "DIRECCION_LEGAL": "Av. Alfonso Ugarte 203 – Selva Alegre",
    "TRANSITO": " Alto Selve Alegre, Av. Roosevelt, Puente Chilina y Av. Obrera",
    "REFERENCIA": "Óvalo Roosevelt",
    "MEDIDA": "12.00X6.00",
    "ANCHO": "12",
    "ALTO": "6",
    "AREA": "72",
    "LATITUD": "-16.3834122",
    "LONGITUD": "-71.5249248",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "1,884,244",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-048 A",
    "ELEMENTO": "ARQ-048",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Puente Chilina ",
    "DIRECCION_LEGAL": "Av. Puente Chilina ",
    "TRANSITO": "Hacia Río Chili con dirección a la municipalidad de Cayma.",
    "REFERENCIA": "A espalda del Parque Ecológico Metropolitano",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.3816248",
    "LONGITUD": "-71.5299338",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,593,666",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-048 B",
    "ELEMENTO": "ARQ-048",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Puente Chilina ",
    "DIRECCION_LEGAL": "Av. Puente Chilina ",
    "TRANSITO": "Hacia Ovalo Roosevelt, Ovalo del Rocoto, Municipalidad distrital de Alto Selva Alegre",
    "REFERENCIA": "A espalda del Parque Ecológico Metropolitano",
    "MEDIDA": "14.40X7.20",
    "ANCHO": "14.4",
    "ALTO": "7.2",
    "AREA": "103.68",
    "LATITUD": "-16.3816248",
    "LONGITUD": "-71.5299338",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,593,666",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-049 A",
    "ELEMENTO": "ARQ-049",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación Km. 7",
    "DIRECCION_LEGAL": "Av. Aviación Km. 7 – Cercado Cerro Colorado",
    "TRANSITO": "Hacia el norte , aereopuerto, terminal pesquero, salida a Juliaca.",
    "REFERENCIA": "Cercano a Kia Import y complejo de prestaciones sociales de EsSalud.",
    "MEDIDA": "12.00X6.00",
    "ANCHO": "12",
    "ALTO": "6",
    "AREA": "72",
    "LATITUD": "-16.3612222",
    "LONGITUD": "-71.5618367",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "1,937,469",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-049 B",
    "ELEMENTO": "ARQ-049",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Aviación Km. 7",
    "DIRECCION_LEGAL": "Av. Aviación Km. 7 – Cercado Cerro Colorado",
    "TRANSITO": "Hacia Av. Primavera, C.C. Arequipa Center, fabrica Soccosani",
    "REFERENCIA": "Cercano a Kia Import y complejo de prestaciones sociales de EsSalud.",
    "MEDIDA": "12.00X6.00",
    "ANCHO": "12",
    "ALTO": "6",
    "AREA": "72",
    "LATITUD": "-16.3614181",
    "LONGITUD": "-71.5617496",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "1,969,057",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-050 A",
    "ELEMENTO": "ARQ-050",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Metropolitana Con Calle Chullos",
    "DIRECCION_LEGAL": "Av. Metropolitana cruce con Calle Chullos - Yanahuara",
    "TRANSITO": "Hacia Av. Víctor Andrés Belaunde con dirección al colegio San Jerónimo.",
    "REFERENCIA": "A 2 cdras. Del centro empresarial Quimera.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3988607",
    "LONGITUD": "-71.5538499",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "1,405,547",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-050 B",
    "ELEMENTO": "ARQ-050",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Metropolitana Con Calle Chullos",
    "DIRECCION_LEGAL": "Av. Metropolitana cruce con Calle Chullos - Yanahuara",
    "TRANSITO": "Hacia Av. Grande con dirección a Cerro Colorado",
    "REFERENCIA": "A 2 cdras. Del centro empresarial Quimera.",
    "MEDIDA": "10.80X5.40",
    "ANCHO": "10.8",
    "ALTO": "5.4",
    "AREA": "58.32",
    "LATITUD": "-16.3988607",
    "LONGITUD": "-71.5538499",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "4,804,029",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-051 A",
    "ELEMENTO": "ARQ-051",
    "CARA": "A",
    "FORMATO": "Unipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. El Ejército Cuadra 7 - Yanahuara",
    "DIRECCION_LEGAL": "Av. El Ejército cdra 7 frente a Mall Plaza",
    "TRANSITO": "Hacia Av. Cayma con dirección al C.C Real Plaza",
    "REFERENCIA": "Frente al C.C Mall Plaza Cayma y Hotel Paititi rodeado de diversos negocios locales",
    "MEDIDA": "9.60X4.80",
    "ANCHO": "9.6",
    "ALTO": "4.8",
    "AREA": "46.08",
    "LATITUD": "-16.3904345",
    "LONGITUD": "-71.5455971",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,407,807",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-052 A",
    "ELEMENTO": "ARQ-052",
    "CARA": "A",
    "FORMATO": "Minipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA DIGITAL",
    "DIRECCION_COMERCIAL": "Óvalo Quiñones",
    "DIRECCION_LEGAL": "Av. Capitán José Abelardo Quiñones altura de la Urbanización Magisterial II - Yanahuara",
    "TRANSITO": "Hacia Av. La Marina con dirección a la Plaza de Armas",
    "REFERENCIA": "Óvalo Quiñones frente a Red de Bancos y rodeado de diversos negocios locales",
    "MEDIDA": "7.68X3.84",
    "ANCHO": "7.68",
    "ALTO": "3.84",
    "AREA": "29.4912",
    "LATITUD": "-16.3972710",
    "LONGITUD": "-71.5472330",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,404,800",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-054 A",
    "ELEMENTO": "ARQ-054",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Daniel Alcides Carrión (Corredor Vitrina)",
    "DIRECCION_LEGAL": "Av. Daniel Alcidés Carrión frente a predio Nº 520",
    "TRANSITO": "Hacia Av. Los Incas con dirección al C.C. La Isla y al Cementerio Apacheta",
    "REFERENCIA": "Frente a la UNSA y próximo al Hospital General",
    "MEDIDA": "10.30X4.80",
    "ANCHO": "10.3",
    "ALTO": "4.8",
    "AREA": "49.44",
    "LATITUD": "-16.4142154",
    "LONGITUD": "-71.5345957",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "979,483",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-054 B",
    "ELEMENTO": "ARQ-054",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Daniel Alcides Carrión (Corredor Vitrina)",
    "DIRECCION_LEGAL": "Av. Daniel Alcidés Carrión frente a predio Nº 520",
    "TRANSITO": "Hacia Av. Venezuela con dirección al Estadio Melgar y Plaza de Armas",
    "REFERENCIA": "Frente a la UNSA y próximo al Hospital General",
    "MEDIDA": "10.30X4.80",
    "ANCHO": "10.3",
    "ALTO": "4.8",
    "AREA": "49.44",
    "LATITUD": "-16.4141519",
    "LONGITUD": "-71.5346194",
    "OBSERVACION": "Elemento con reflector solar",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,386,250",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-055 A",
    "ELEMENTO": "ARQ-055",
    "CARA": "A",
    "FORMATO": "Unipolar Digital",
    "TIPO": "DIGITAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA DIGITAL",
    "DIRECCION_COMERCIAL": "Av. Porongoche Cdra. 5",
    "DIRECCION_LEGAL": "Av. Porongoche 506",
    "TRANSITO": "Hacia Av. Los Incas con dirección al Distrito de Mariano Melgar",
    "REFERENCIA": "Frente al Mall Aventura Plaza, HM y  al costado de estilos",
    "MEDIDA": "12.80X7.70",
    "ANCHO": "12.8",
    "ALTO": "7.7",
    "AREA": "98.56",
    "LATITUD": "-16.4164748",
    "LONGITUD": "-71.5155245",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,123,914",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-055 B",
    "ELEMENTO": "ARQ-055",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Porongoche Cdra. 5",
    "DIRECCION_LEGAL": "Av. Porongoche 506",
    "TRANSITO": "Hacia Av. Pizarro con dirección a la Av. Guardia Civil.",
    "REFERENCIA": "Frente al Mall Aventura Plaza, HM y  al costado de estilos",
    "MEDIDA": "12.85X5.80",
    "ANCHO": "12.85",
    "ALTO": "5.8",
    "AREA": "74.53",
    "LATITUD": "-16.4164748",
    "LONGITUD": "-71.5155245",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,211,834",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-056 U",
    "ELEMENTO": "ARQ-056",
    "CARA": "U",
    "FORMATO": "Banderola",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. José Abelardo Quiñones alt. cruce con Chullo",
    "DIRECCION_LEGAL": "Av. Urbanización Los Cedros Mz. (F) Lote (3) - Yanahuara",
    "TRANSITO": "Hacia Cayma, la Av. El Ejército, Real Plaza y Mall de Arequipa.",
    "REFERENCIA": "Alt. Parque del Avión y frente al Parque de La Familia.",
    "MEDIDA": "7.50X11.80",
    "ANCHO": "7.5",
    "ALTO": "11.8",
    "AREA": "88.5",
    "LATITUD": "-16.3946670",
    "LONGITUD": "-71.5483330",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,071,687",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-057 A",
    "ELEMENTO": "ARQ-057",
    "CARA": "A",
    "FORMATO": "Corona",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Ejército cruce con Av. Cayma",
    "DIRECCION_LEGAL": "Av. Ejército N° 903",
    "TRANSITO": "Hacia el distrito de Cerro Colorado, Arequipa Center, C.C Real Plaza.",
    "REFERENCIA": "Frente a Scotiabank, al lado de Mifarma y rodeado de diversos negocios locales.",
    "MEDIDA": "9.70X9.70",
    "ANCHO": "9.7",
    "ALTO": "9.7",
    "AREA": "94.09",
    "LATITUD": "-16.3896670",
    "LONGITUD": "-71.5479720",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,814,971",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-057 B",
    "ELEMENTO": "ARQ-057",
    "CARA": "B",
    "FORMATO": "Corona",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Ejército cruce con Av. Cayma",
    "DIRECCION_LEGAL": "Av. Ejército N° 903",
    "TRANSITO": "Hacia Av. Trinidad Morán y Óvalo Quiñones",
    "REFERENCIA": "Frente a Scotiabank, al lado de Mifarma y rodeado de diversos negocios locales.",
    "MEDIDA": "10.10X9.70",
    "ANCHO": "10.1",
    "ALTO": "9.7",
    "AREA": "97.97",
    "LATITUD": "-16.3896670",
    "LONGITUD": "-71.5479720",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,223,447",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-057 C",
    "ELEMENTO": "ARQ-057",
    "CARA": "C",
    "FORMATO": "Corona",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Ejército cruce con Av. Cayma",
    "DIRECCION_LEGAL": "Av. Ejército N° 903",
    "TRANSITO": "Hacia C.C. Mall Plaza, Av. La Marina y Plaza de Armas de Arequipa.",
    "REFERENCIA": "Frente a Scotiabank, al lado de Mifarma y rodeado de diversos negocios locales.",
    "MEDIDA": "9.70X9.70",
    "ANCHO": "9.7",
    "ALTO": "9.7",
    "AREA": "94.09",
    "LATITUD": "-16.3896670",
    "LONGITUD": "-71.5479720",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "4,257,561",
    "PROPIEDAD": "PP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-061 A",
    "ELEMENTO": "ARQ-061",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Mariscal Cáceres cruce con Av. Jorge Chávez",
    "DIRECCION_LEGAL": "Av. Mariscal Cáceres cruce con Av. Jorge Chávez",
    "TRANSITO": "Hacia la Av. Parra, tienda concesionaria de motos, Instituto del Sur, Plaza de Armas de Arequipa.",
    "REFERENCIA": "Frente a la Parroquia Nuestra Señora Del Pilar y cerca al Estadio Melgar.",
    "MEDIDA": "10.30X5.20",
    "ANCHO": "10.3",
    "ALTO": "5.2",
    "AREA": "53.56",
    "LATITUD": "-16.4092420",
    "LONGITUD": "-71.5372250",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,786,383",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-061 B",
    "ELEMENTO": "ARQ-061",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Av. Mariscal Cáceres cruce con Av. Jorge Chávez",
    "DIRECCION_LEGAL": "Av. Mariscal Cáceres cruce con Av. Jorge Chávez",
    "TRANSITO": "Hacia el  Hospital Regional Honorio Delgado Espinoza, Av. Los Incas y Ovalo Dolores. ",
    "REFERENCIA": "Frente a la Parroquia Nuestra Señora Del Pilar y cerca al Estadio Melgar.",
    "MEDIDA": "10.30X5.20",
    "ANCHO": "10.3",
    "ALTO": "5.2",
    "AREA": "53.56",
    "LATITUD": "-16.4092420",
    "LONGITUD": "-71.5372250",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "3,044,584",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-063 A",
    "ELEMENTO": "ARQ-063",
    "CARA": "A",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Puente San Martín cruce con Av. La Marina",
    "DIRECCION_LEGAL": "Puente San Martín cruce con Av. La Marina",
    "TRANSITO": "Hacia el Ovalo De Vallecito, Av. Parra, Universidad UTP y  Estadio Melgar.",
    "REFERENCIA": "Puente San Martín, Cerca de la Cdra. 1 de la Av. La Marina y frente al Grifo  Primax Vallecito.",
    "MEDIDA": "10.30X5.20",
    "ANCHO": "10.3",
    "ALTO": "5.2",
    "AREA": "53.56",
    "LATITUD": "-16.4039446",
    "LONGITUD": "-71.5441555",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,801,910",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ARQ-063 B",
    "ELEMENTO": "ARQ-063",
    "CARA": "B",
    "FORMATO": "Torre Unipolar",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Arequipa",
    "DISTRITO": "",
    "ZONA": "PROVINCIA",
    "DIRECCION_COMERCIAL": "Puente San Martín cruce con Av. La Marina",
    "DIRECCION_LEGAL": "Puente San Martín cruce con Av. La Marina",
    "TRANSITO": "Hacia el Ovalo De Vallecito, Av. Parra, Universidad UTP y  Estadio Melgar.",
    "REFERENCIA": "Puente San Martín, Cerca de la Cdra. 1 de la Av. La Marina y frente al Grifo  Primax Vallecito.",
    "MEDIDA": "10.30X5.20",
    "ANCHO": "10.3",
    "ALTO": "5.2",
    "AREA": "53.56",
    "LATITUD": "-16.4039446",
    "LONGITUD": "-71.5441555",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "COMERCIAL",
    "AUDIENCIA": "2,762,846",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ATE-001 A",
    "ELEMENTO": "ATE-001",
    "CARA": "A",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Ate",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Cdra. 42",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón Cdra. 42",
    "TRANSITO": "Tránsito hacia el C.C. Mall Aventura Plaza con dirección a la Victoria",
    "REFERENCIA": "Frente a Grifo Repsol y C.C. Real Plaza Puruchuco",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0411790",
    "LONGITUD": "-76.9347470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "7,121,957",
    "PROPIEDAD": "VP"
  },
  {
    "CODIGO_PROVEEDOR": "ATE-001 B",
    "ELEMENTO": "ATE-001",
    "CARA": "B",
    "FORMATO": "Torre Minipolar ",
    "TIPO": "TRADICIONAL",
    "PROVEEDOR": "JMT OUTDOORS",
    "DEPARTAMENTO": "Lima",
    "DISTRITO": "Ate",
    "ZONA": "LIMA",
    "DIRECCION_COMERCIAL": "Av. Nicolás Ayllón Cdra. 42",
    "DIRECCION_LEGAL": "Av. Nicolás Ayllón Cdra. 42",
    "TRANSITO": "Tránsito hacia el C.C. Mall Aventura Plaza con dirección a la Victoria",
    "REFERENCIA": "Frente a Grifo Repsol y C.C. Real Plaza Puruchuco",
    "MEDIDA": "8.00X4.00",
    "ANCHO": "8",
    "ALTO": "4",
    "AREA": "32",
    "LATITUD": "-12.0411790",
    "LONGITUD": "-76.9347470",
    "OBSERVACION": "",
    "ESTADO_PRODUCTO": "DISPONIBLE",
    "CONDICION_MERCADO": "PARA IMPULSAR",
    "AUDIENCIA": "6,981,441",
    "PROPIEDAD": "VP"
  }
];

// Transform logic and export
export const INVENTORY: Billboard[] = RAW_DATA
  .filter(item => item.CODIGO_PROVEEDOR && item.CODIGO_PROVEEDOR.length < 20 && item.LATITUD)
  .map((item, index) => ({
    id: `${item.CODIGO_PROVEEDOR}-${index}`,
    codigo: item.CODIGO_PROVEEDOR || '',
    elemento: item.ELEMENTO || '',
    cara: item.CARA || '',
    formato: item.FORMATO || '',
    distrito: item.DISTRITO || '',
    tipo: item.TIPO || '',
    medida: item.MEDIDA || '',
    ancho: item.ANCHO || '',
    alto: item.ALTO || '',
    audiencia: parseInt((item.AUDIENCIA || '0').replace(/,/g, ''), 10) || 0,
    direccionComercial: item.DIRECCION_COMERCIAL || '',
    direccionLegal: item.DIRECCION_LEGAL || '',
    departamento: item.DEPARTAMENTO || '',
    zona: item.ZONA || '',
    latitud: parseFloat(item.LATITUD || '0'),
    longitud: parseFloat(item.LONGITUD || '0'),
    observacion: item.OBSERVACION || ''
  }));

export const DEPARTMENT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.departamento).filter(Boolean))).sort();
export const DISTRICT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.distrito).filter(Boolean))).sort();
export const ELEMENT_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.elemento).filter(Boolean))).sort();
export const TYPE_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.tipo).filter(Boolean))).sort();
export const ZONE_OPTIONS = Array.from(new Set(INVENTORY.map(i => i.zona).filter(Boolean))).sort();
